### PR TITLE
Added entity model

### LINKED ISSUE #9: Add entity api endpoints
Add support for entity:
* GET
* POST
* PUT
* DELETE

### PR DESCRIPTION
**Pull request by eugene-p**
Added entity model unittest
Closes #9, #10 , #31

### CODE REVIEW

**Comment by eugene-p** [comment]
So how would I fix those? Not really a repetition :(

**Comment by eugene-p** [comment]
split into separate files?

**Comment by cedar-technologies** [comment]
I will look at it soon, and see if we need to change some settings on code climate

**Comment by cedar-technologies** [comment]
Those are not duplicates...

**Pull request merged**
