### PR TITLE
Refactor docker

### PR DESCRIPTION
**Pull request by cedar-technologies**
Refactor docker and add migration

### CODE REVIEW

**Review by jlaplante333 — CHANGES_REQUESTED** [review]
Correct C12 error (Code Climate parser error?) It is complaining about the ":"

**Comment by cedar-technologies** [comment]
Not part of this pull request

**Comment by cedar-technologies** [comment]
Create a separate issue for that, but we don't review stuff that are not part of the request

**Comment by jlaplante333** [comment]
> Not part of this pull request

image
So code climate encountering errors for a request should be considered a new issue? Ok. How do I review the rest then?

**Review by jlaplante333 — APPROVED** [review]

**Pull request merged**
